# Generated by Django 2.2.7 on 2019-11-30 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('about', models.TextField(max_length=50000, verbose_name='About')),
                ('status', models.CharField(choices=[('IDE', 'Idea'), ('IDV', 'In dev'), ('DEB', 'Debug'), ('COO', 'Сooked')], max_length=3, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_release', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date added')),
                ('stars', models.PositiveIntegerField(default=0, verbose_name='Stars')),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Authors')),
                ('links', models.ManyToManyField(to='changellenge_web.Links', verbose_name='Links')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServicesRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Children', to='changellenge_web.Services', verbose_name='Children')),
                ('parents', models.ManyToManyField(related_name='Parents', to='changellenge_web.Services', verbose_name='Parents')),
            ],
            options={
                'verbose_name': 'Service relation',
                'verbose_name_plural': 'Service relations',
            },
        ),
    ]
