# Generated by Django 2.2.7 on 2019-11-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changellenge_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='links',
            field=models.ManyToManyField(blank=True, to='changellenge_web.Links', verbose_name='Links'),
        ),
    ]
