# Generated by Django 2.2.7 on 2019-11-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changellenge_web', '0005_auto_20191130_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaboutpreset',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
