# Generated by Django 2.2.7 on 2019-11-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changellenge_web', '0007_auto_20191130_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': "Tag's",
            },
        ),
        migrations.RemoveField(
            model_name='services',
            name='date_release',
        ),
        migrations.RemoveField(
            model_name='services',
            name='links',
        ),
        migrations.AddField(
            model_name='services',
            name='tags',
            field=models.ManyToManyField(to='changellenge_web.Tag', verbose_name="Tag's"),
        ),
    ]
